export const GET_CHART_DATA = "GET_CHART_DATA";
export const SET_PIE_CHART_DATA = "SET_PIE_CHART_DATA";
export const SET_BAR_CHART_DATA = "SET_BAR_CHART_DATA";
export const SET_VIEW_TYPE = "SET_VIEW_TYPE";
export const SET_INTERNAL_VIEW_TYPE = "SET_INTERNAL_VIEW_TYPE";
