export const GET_PAST_NOTIFICATIONS = "GET_PAST_NOTIFICATIONS";
export const GET_PRESENT_NOTIFICATIONS = "GET_PRESENT_NOTIFICATIONS";
export const GET_FUTURE_NOTIFICATIONS = "GET_FUTURE_NOTIFICATIONS";
export const FETCHING_NOTIFICATIONS = "FETCHING_NOTIFICATIONS";