export const GET_PROFILES = 'GET_PROFILES';
export const GET_PROFILES_SUCCESS = 'GET_PROFILES_SUCCESS';
export const GET_PROFILES_FAILURE = 'GET_PROFILES_FAILURE';
export const ADD_PROFILE = 'ADD_PROFILE';
export const ADD_PROFILE_SUCCESS = 'ADD_PROFILE_SUCCESS';
export const ADD_PROFILE_FAILURE = 'ADD_PROFILE_FAILURE';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILURE = 'EDIT_PROFILE_FAILURE';
export const VIEW_PROFILE = 'VIEW_PROFILE';
export const VIEW_PROFILE_SUCCESS = 'VIEW_PROFILE_SUCCESS';
export const VIEW_PROFILE_FAILURE = 'VIEW_PROFILE_FAILURE';

