export const OPTION_CHANGE = 'OPTION_CHANGE';
export const NEW_OPTION_CREATE = 'NEW_OPTION_CREATE';
export const NEW_OPTION_CREATE_SUCCESS = 'NEW_OPTION_CREATE_SUCCESS';
export const NEW_OPTION_CREATE_FAILURE = 'NEW_OPTION_CREATE_FAILURE';